import type {Metadata} from 'next'
import {Footer} from "@/components/layout/Footer";
import {getDictionary} from "@/utils/dictionaries";
import {Navbar} from "@/components/layout/navbar/Navbar";
import {LeftShorCut} from "@/components/layout/LeftShorCut";


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function Layout({
                                             children,
                                             params
                                         }: {
    children: React.ReactNode,
    params: { lang: string }
}) {

    const t = await getDictionary(params.lang);
    return (
        <div className='relative'>
            <LeftShorCut />
            <Navbar dictionary={t} lang={params.lang} />
            {children}
            <Footer/>
        </div>
    )
}
