import type {Metadata} from 'next'
import {Footer} from "@/components/layout/Footer";
import {getDictionary} from "@/utils/dictionaries";
import {Navbar} from "@/components/layout/Navbar";


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function Layout({
                                             children,
                                             params
                                         }: {
    children: React.ReactNode,
    params: { lang: string }
}) {

    const t = await getDictionary(params.lang);
    return (
        <div className='relative'>
            <div className=' fixed bottom-10 left-10 '>
                <p>p</p>
                <p>p</p>
                <p>p</p>
                <p>p</p>
                <p>p</p>
                <p>p</p>
                <p>p</p>
                <p>p</p>
                <p>p</p>
                <p>p</p>
            </div>
            <Navbar dictionary={t} lang={params.lang} />
            {children}
            <Footer/>
            <div className=' fixed bottom-[120px] right-[-40px] vertical-text'>
                <p>alexcarvajal2404@gmail.com</p>
            </div>
        </div>
    )
}
